In [85]:
titanic = pd.read_csv('https://bit.ly/3HaMAtZ')
titanic.groupby(['Embarked', 'Pclass'])['Age'].median()

Embarked  Pclass
C         1         35.90
          2         27.00
          3         27.75
Q         1         38.50
          2         30.00
          3         27.00
S         1         35.90
          2         30.00
          3         26.00
Name: Age, dtype: float64

In [103]:
titanic = pd.read_csv('https://bit.ly/3HaMAtZ')
titanic

Survived  Pclass     Sex    Age  SibSp  Parch     Fare Embarked  \
0           0       3    male  22.00      1      0   7.2500        S   
1           1       1  female  38.00      1      0  71.2833        C   
2           1       3  female  26.00      0      0   7.9250        S   
3           1       1  female  35.00      1      0  53.1000        S   
4           0       3    male  35.00      0      0   8.0500        S   
..        ...     ...     ...    ...    ...    ...      ...      ...   
886         0       2    male  27.00      0      0  13.0000        S   
887         1       1  female  19.00      0      0  30.0000        S   
888         0       3  female  21.77      1      2  23.4500        S   
889         1       1    male  26.00      0      0  30.0000        C   
890         0       3    male  32.00      0      0   7.7500        Q   

     AgeGroup  Family  Age_scale1  
0    Age21_30       2    0.271174  
1    Age31_40       2    0.472229  
2    Age21_30       1    0.321438  
3    Age31_40       2    0.434531  
4    Age31_40       1    0.434531  
..        ...     ...         ...  
886  Age21_30       1    0.334004  
887  Age11_20       1    0.233476  
888  Age21_30       4    0.268283  
889  Age21_30       1    0.321438  
890  Age31_40       1    0.396833  

[891 rows x 11 columns]

In [105]:
titanic.loc[(titanic['Pclass'] == 2) & (titanic['Sex'] == 'male')]['Age'].mean()

30.876481481481477

In [86]:
a = [[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]]

In [92]:
a = np.array([[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]])

In [93]:
a[1:3, 1:3]

array([[16, 17],
       [20, 21]])

In [94]:
a[1:, 1:3]

array([[16, 17],
       [20, 21]])

In [95]:
a[-2:, -3:-1]

array([[16, 17],
       [20, 21]])

In [96]:
a[1:3, 1:3]

array([[16, 17],
       [20, 21]])