# Keras로 Linear&Logistic Regression 맛보기!

#### 실습목표<br>
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(0,20))
y = x * 2 -1 

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [ ]:
# 1번 청소 : 이미 만들어진 모델이 있다면 그 모델을 없애줘
keras.backend.clear_session()

# 2번 모델 선언
model = keras.models.Sequential()

# 3번 모델 블록 조립
model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1) )

## 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,)) )

# 4번 컴파일 
model.compile(loss='mse',
              optimizer='adam')
# loss : 내가 생성한 모델과 실제 값을 무슨 방법으로 비교할래 
# optimizer : gradient decent를 어떤 방식으로 진행할 것 인가

In [ ]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 517ms/step - loss: 1464.5565
Epoch 2/10
1/1 [==============================] - 0s 8ms/step - loss: 1463.6412
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 1462.7263
Epoch 4/10
1/1 [==============================] - 0s 11ms/step - loss: 1461.8116
Epoch 5/10
1/1 [==============================] - 0s 9ms/step - loss: 1460.8972
Epoch 6/10
1/1 [==============================] - 0s 9ms/step - loss: 1459.9832
Epoch 7/10
1/1 [==============================] - 0s 10ms/step - loss: 1459.0696
Epoch 8/10
1/1 [==============================] - 0s 8ms/step - loss: 1458.1560
Epoch 9/10
1/1 [==============================] - 0s 8ms/step - loss: 1457.2429
Epoch 10/10
1/1 [==============================] - 0s 7ms/step - loss: 1456.3302


In [ ]:
print(y)

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [ ]:
model.predict(x)[:5].reshape(-1) # 가로 형태로 보기

array([ 0.00999895, -1.5002632 , -3.0105252 , -4.5207877 , -6.0310497 ],
      dtype=float32)

In [ ]:
y[:5]

array([10,  7,  4,  1, -2])

## Now, Your turn!

In [ ]:
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(0,20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [ ]:
# 세션 청소
keras.backend.clear_session()

# 모델 선언
model1 = keras.models.Sequential()

# 모델 블록 조립
model1.add(keras.layers.Input(shape=(1,)))
model1.add(keras.layers.Dense(1))

# 컴파일
model1.compile(loss='mse', optimizer='adam')

In [ ]:
model1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.predict(x).reshape(-1)

array([ 9.9989474e-03, -1.5002632e+00, -3.0105252e+00, -4.5207877e+00,
       -6.0310497e+00, -7.5413117e+00, -9.0515738e+00, -1.0561835e+01,
       -1.2072098e+01, -1.3582360e+01, -1.5092622e+01, -1.6602884e+01,
       -1.8113148e+01, -1.9623409e+01, -2.1133671e+01, -2.2643934e+01,
       -2.4154196e+01, -2.5664457e+01, -2.7174721e+01, -2.8684982e+01],
      dtype=float32)

## Quick Logistic Regression!

In [ ]:
model1.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 335ms/step - loss: 225.7800
Epoch 2/10
1/1 [==============================] - 0s 8ms/step - loss: 225.4480
Epoch 3/10
1/1 [==============================] - 0s 13ms/step - loss: 225.1162
Epoch 4/10
1/1 [==============================] - 0s 15ms/step - loss: 224.7848
Epoch 5/10
1/1 [==============================] - 0s 8ms/step - loss: 224.4538
Epoch 6/10
1/1 [==============================] - 0s 8ms/step - loss: 224.1230
Epoch 7/10
1/1 [==============================] - 0s 7ms/step - loss: 223.7924
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: 223.4623
Epoch 9/10
1/1 [==============================] - 0s 9ms/step - loss: 223.1325
Epoch 10/10
1/1 [==============================] - 0s 7ms/step - loss: 222.8029


In [ ]:
import tensorflow as tf
import tensorflow.keras as keras

import numpy as np

In [ ]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [ ]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# model에 순차적으로 레이어를 쌓아가겠다는 의도!
model = keras.models.Sequential()

# model에 인풋 값을 받는 레이어를 넣음
model.add( keras.layers.Input(shape=(1,)) )
# model에 Dense 레이어를 넣을거야 (최초의 레이어) : weight를 곱하고, bias를 더해주는 과정
model.add( keras.layers.Dense(1, activation='sigmoid') )
# 이진분류에 맞게 값이 나옴


# 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,), activation='sigmoid') )

# 컴파일 해주렴
model.compile(loss = 'binary_crossentropy',
              optimizer = 'adam',
              metrics=['accuracy'])

In [ ]:
# 데이터를 넣어서 학습시키자!
model.fit(x[:15], y[:15], epochs=10, verbose=1)

# 결과 출력해줘!
print(y[15:])
print(model.predict(x[15:]))

Epoch 1/10
1/1 [==============================] - 0s 475ms/step - loss: 6.6861 - accuracy: 0.6667
Epoch 2/10
1/1 [==============================] - 0s 9ms/step - loss: 6.6818 - accuracy: 0.6000
Epoch 3/10
1/1 [==============================] - 0s 8ms/step - loss: 6.6776 - accuracy: 0.6000
Epoch 4/10
1/1 [==============================] - 0s 8ms/step - loss: 6.6733 - accuracy: 0.6000
Epoch 5/10
1/1 [==============================] - 0s 7ms/step - loss: 6.6690 - accuracy: 0.6000
Epoch 6/10
1/1 [==============================] - 0s 10ms/step - loss: 6.6648 - accuracy: 0.6000
Epoch 7/10
1/1 [==============================] - 0s 10ms/step - loss: 6.6605 - accuracy: 0.6000
Epoch 8/10
1/1 [==============================] - 0s 8ms/step - loss: 6.6562 - accuracy: 0.6000
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 6.6519 - accuracy: 0.6000
Epoch 10/10
1/1 [==============================] - 0s 5ms/step - loss: 6.6477 - accuracy: 0.6000
[1 1 1 1 1]
[[1.9033143e-11]
 [3.66

## Now, Your turn!

In [ ]:
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(0,40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [ ]:
keras.backend.clear_session()# 메모리 문제 때문에 그렇다. 안그러면 남아서 _1. _2로 모델들이 추가된다.

model = keras.models.Sequential()

model.add( keras.layers.Input(shape=(1,)) )
model.add(keras.layers.Dense(1, activation='sigmoid'))# 컴파일 해주렴 

model.compile(loss = 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])# loss를 보고 자동으로 판단해주는 정확도 
# metrics=keras.metrics.BinaryAccuracy(threshold=지정가능)
# 분포와 분포를 비교하는데 사용하는데 사용하는 crossentropy를 쓰는데 직관적이진 않다.
# 정확도를 넣어서 비교하기 쉽게 확인할 수 있다.

In [ ]:
model.fit(x[:15], y[:15], epochs=10, verbose=1)# 이진분류는 0.5보다 클 때 1 작으면 0이다. 그래서 예측이 떨어진다.

Epoch 1/10
1/1 [==============================] - 1s 548ms/step - loss: 4.9474 - accuracy: 0.0667
Epoch 2/10
1/1 [==============================] - 0s 11ms/step - loss: 4.9396 - accuracy: 0.0667
Epoch 3/10
1/1 [==============================] - 0s 8ms/step - loss: 4.9318 - accuracy: 0.0667
Epoch 4/10
1/1 [==============================] - 0s 8ms/step - loss: 4.9240 - accuracy: 0.0667
Epoch 5/10
1/1 [==============================] - 0s 9ms/step - loss: 4.9162 - accuracy: 0.0667
Epoch 6/10
1/1 [==============================] - 0s 8ms/step - loss: 4.9084 - accuracy: 0.0667
Epoch 7/10
1/1 [==============================] - 0s 13ms/step - loss: 4.9006 - accuracy: 0.0667
Epoch 8/10
1/1 [==============================] - 0s 13ms/step - loss: 4.8928 - accuracy: 0.0667
Epoch 9/10
1/1 [==============================] - 0s 13ms/step - loss: 4.8850 - accuracy: 0.0667
Epoch 10/10
1/1 [==============================] - 0s 12ms/step - loss: 4.8772 - accuracy: 0.0667


In [ ]:
# 결과 출력해줘!
print(y[15:])
print(model.predict(x[15:]))

[0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[[0.9999635 ]
 [0.9999816 ]
 [0.9999907 ]
 [0.99999523]
 [0.9999976 ]
 [0.99999875]
 [0.9999994 ]
 [0.99999964]
 [0.9999999 ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]
 [1.        ]]
