# Keras로 Linear&Logistic Regression 맛보기!

#### 실습목표<br>
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [ ]:
import tensorflow as tf
from tensorflow import keras
# import keras : 외부 keras, 원래는 따로 운영이 되어있었는데 개발자가 구글에 들어가게 되어서 통합됨 위의 걸로 쓰면 됨
# 현업에서는 keras 더 많이 사용 함 , 연구실은 pytorch
import numpy as np

In [ ]:
x = np.array(range(0,20)) 
y = x * 2 -1

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [ ]:
# 자주 해줘야 함!
x.shape, y.shape
# input layer 안에 x라는 값을 하나 가지고 있다고 이해
# x가 데이터 프레임 하나의 feature라고 생각

((20,), (20,))

In [ ]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1)(input_layer)# 사슬처럼 연결해주어야 함

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 컴파일 해주렴
model.compile(loss = 'mse', optimizer = 'adam')

In [ ]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 517ms/step - loss: 797.2366
Epoch 2/10
1/1 [==============================] - 0s 10ms/step - loss: 796.5615
Epoch 3/10
1/1 [==============================] - 0s 9ms/step - loss: 795.8868
Epoch 4/10
1/1 [==============================] - 0s 8ms/step - loss: 795.2124
Epoch 5/10
1/1 [==============================] - 0s 11ms/step - loss: 794.5382
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 793.8644
Epoch 7/10
1/1 [==============================] - 0s 7ms/step - loss: 793.1909
Epoch 8/10
1/1 [==============================] - 0s 10ms/step - loss: 792.5177
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 791.8448
Epoch 10/10
1/1 [==============================] - 0s 7ms/step - loss: 791.1723


In [ ]:
# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]
[ 9.9985702e-03 -5.9723639e-01 -1.2044713e+00 -1.8117063e+00
 -2.4189413e+00 -3.0261762e+00 -3.6334112e+00 -4.2406459e+00
 -4.8478808e+00 -5.4551158e+00 -6.0623507e+00 -6.6695857e+00
 -7.2768207e+00 -7.8840556e+00 -8.4912910e+00 -9.0985260e+00
 -9.7057610e+00 -1.0312996e+01 -1.0920231e+01 -1.1527466e+01]


## Now, Your turn!

In [1]:
from tensorflow import keras
import numpy as np

In [3]:
x = np.array(range(0,20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [6]:
keras.backend.clear_session()

il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1)(il)

model = keras.models.Model(inputs=il, outputs=ol)

model.compile(loss='mse', optimizer='adam')

In [7]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 531ms/step - loss: 1288.2219
Epoch 2/10
1/1 [==============================] - 0s 10ms/step - loss: 1287.3773
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 1286.5331
Epoch 4/10
1/1 [==============================] - 0s 12ms/step - loss: 1285.6891
Epoch 5/10
1/1 [==============================] - 0s 8ms/step - loss: 1284.8455
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 1284.0022
Epoch 7/10
1/1 [==============================] - 0s 5ms/step - loss: 1283.1591
Epoch 8/10
1/1 [==============================] - 0s 10ms/step - loss: 1282.3164
Epoch 9/10
1/1 [==============================] - 0s 7ms/step - loss: 1281.4740
Epoch 10/10
1/1 [==============================] - 0s 7ms/step - loss: 1280.6321


In [8]:
model.predict(x).reshape(-1)

array([-9.9987667e-03,  9.4500315e-01,  1.9000050e+00,  2.8550069e+00,
        3.8100088e+00,  4.7650108e+00,  5.7200127e+00,  6.6750145e+00,
        7.6300163e+00,  8.5850191e+00,  9.5400209e+00,  1.0495023e+01,
        1.1450025e+01,  1.2405026e+01,  1.3360028e+01,  1.4315030e+01,
        1.5270032e+01,  1.6225035e+01,  1.7180037e+01,  1.8135038e+01],
      dtype=float32)

In [9]:
y

array([ 10,   7,   4,   1,  -2,  -5,  -8, -11, -14, -17, -20, -23, -26,
       -29, -32, -35, -38, -41, -44, -47])

## Quick Logistic Regression!

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

In [ ]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)


# 컴파일 해주렴
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [ ]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

## Now, Your turn!

In [10]:
from tensorflow import keras

In [11]:
x = np.array(range(0,40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [17]:
keras.backend.clear_session()

il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1, activation='sigmoid')(il)

model = keras.models.Model(inputs=il, outputs=ol)

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [18]:
model.fit(x, y, epochs=100, verbose=1) # loss값은 낮을 수록 좋음

Epoch 1/100
2/2 [==============================] - 1s 8ms/step - loss: 2.0617 - accuracy: 0.5250
Epoch 2/100
2/2 [==============================] - 0s 5ms/step - loss: 2.0514 - accuracy: 0.5250
Epoch 3/100
2/2 [==============================] - 0s 5ms/step - loss: 2.0422 - accuracy: 0.5250
Epoch 4/100
2/2 [==============================] - 0s 7ms/step - loss: 2.0325 - accuracy: 0.5250
Epoch 5/100
2/2 [==============================] - 0s 6ms/step - loss: 2.0232 - accuracy: 0.5250
Epoch 6/100
2/2 [==============================] - 0s 5ms/step - loss: 2.0133 - accuracy: 0.5250
Epoch 7/100
2/2 [==============================] - 0s 5ms/step - loss: 2.0044 - accuracy: 0.5250
Epoch 8/100
2/2 [==============================] - 0s 4ms/step - loss: 1.9951 - accuracy: 0.5250
Epoch 9/100
2/2 [==============================] - 0s 4ms/step - loss: 1.9853 - accuracy: 0.5250
Epoch 10/100
2/2 [==============================] - 0s 4ms/step - loss: 1.9765 - accuracy: 0.5250
Epoch 11/100
2/2 [===========

In [19]:
print(model.predict(x).reshape(-1))
print(y)

[0.45226648 0.51013434 0.5677318  0.6235546  0.6762789  0.72487694
 0.76867485 0.8073534  0.8409033  0.86955434 0.8936981  0.913816
 0.930423   0.944026   0.9550978  0.9640629  0.9712918  0.9771012
 0.98175704 0.98548037 0.9884526  0.9908222  0.99270904 0.99421024
 0.9954039  0.9963523  0.9971055  0.99770355 0.99817836 0.99855506
 0.9988539  0.99909115 0.99927914 0.9994284  0.99954677 0.9996406
 0.999715   0.999774   0.99982077 0.9998579 ]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]
