# Keras로 Linear&Logistic Regression 조금 더 맛보기

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

# Linear Regression on 쬐금 더 어려운 데이터

In [ ]:
from sklearn.datasets import load_boston

In [ ]:
boston = load_boston()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [ ]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [ ]:
from tensorflow.python import metrics
keras.backend.clear_session()

model = keras.models.Sequential()

model.add(keras.layers.Input(shape=(13, )))
model.add(keras.layers.Dense(13))

model.compile(loss='mse', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(x, y, epochs=100, verbose=1)

Epoch 1/100
16/16 [==============================] - 0s 2ms/step - loss: 24265.9121 - accuracy: 0.0020
Epoch 2/100
16/16 [==============================] - 0s 2ms/step - loss: 20972.5000 - accuracy: 0.0020
Epoch 3/100
16/16 [==============================] - 0s 2ms/step - loss: 18172.6855 - accuracy: 0.0020
Epoch 4/100
16/16 [==============================] - 0s 2ms/step - loss: 15754.3477 - accuracy: 0.0020
Epoch 5/100
16/16 [==============================] - 0s 2ms/step - loss: 13683.2695 - accuracy: 0.0020
Epoch 6/100
16/16 [==============================] - 0s 2ms/step - loss: 11899.7334 - accuracy: 0.0020
Epoch 7/100
16/16 [==============================] - 0s 2ms/step - loss: 10358.9170 - accuracy: 0.0020
Epoch 8/100
16/16 [==============================] - 0s 2ms/step - loss: 9003.2959 - accuracy: 0.0020
Epoch 9/100
16/16 [==============================] - 0s 2ms/step - loss: 7836.8579 - accuracy: 0.0020
Epoch 10/100
16/16 [==============================] - 0s 2ms/step - loss: 6

In [ ]:
model.predict(x)[:15].reshape(-1)

array([31.762983 , 25.071917 , 23.48764  , 29.441273 , 21.086197 ,
       25.643297 , 26.390448 , 28.064335 , 20.23883  , 28.1612   ,
       21.37661  , 22.50311  , 24.13377  , 24.688837 , 33.016014 ,
       22.348362 , 24.620697 , 25.748138 , 23.719257 , 20.192719 ,
       17.654346 , 28.439938 , 17.913406 , 27.330572 , 17.152773 ,
       22.820599 , 24.582693 , 29.455889 , 24.039999 , 25.031324 ,
       25.145725 , 24.039719 , 21.026653 , 23.362976 , 23.99771  ,
       23.636032 , 18.65091  , 22.020758 , 24.986992 , 24.154724 ,
       24.66453  , 22.571491 , 24.607615 , 23.691875 , 25.445765 ,
       22.08546  , 25.849394 , 22.809443 , 28.816164 ,  9.995959 ,
       24.701372 , 25.716314 , 24.240913 , 26.394245 , 21.989744 ,
       24.366665 , 23.923618 , 25.356901 , 21.771667 , 23.261162 ,
       25.041975 , 25.925207 , 14.319986 , 22.235624 , 24.611532 ,
       24.686522 , 27.502512 , 21.66231  , 24.887228 , 23.599611 ,
       25.263273 , 21.091122 , 22.521229 , 25.198189 , 25.1610

In [ ]:
y[:15]

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2])

# Logistic Regression 쬐금 더 어려운 데이터

In [15]:
from sklearn.datasets import load_breast_cancer

In [16]:
cancer = load_breast_cancer()

In [18]:
x = cancer.data
y = cancer.target

# 모양 확인해볼 것
x.shape, y.shape

((569, 30), (569,))

In [25]:
keras.backend.clear_session()
model = keras.models.Sequential()
model.add(keras.layers.Input(shape=(30,)))
model.add(keras.layers.Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(x, y, epochs=100, verbose=1)

Epoch 1/100
18/18 [==============================] - 0s 2ms/step - loss: 142.5019 - accuracy: 0.3726
Epoch 2/100
18/18 [==============================] - 0s 2ms/step - loss: 128.1943 - accuracy: 0.3726
Epoch 3/100
18/18 [==============================] - 0s 2ms/step - loss: 113.8618 - accuracy: 0.3726
Epoch 4/100
18/18 [==============================] - 0s 2ms/step - loss: 99.4113 - accuracy: 0.3726
Epoch 5/100
18/18 [==============================] - 0s 2ms/step - loss: 85.1803 - accuracy: 0.3726
Epoch 6/100
18/18 [==============================] - 0s 2ms/step - loss: 70.6923 - accuracy: 0.3726
Epoch 7/100
18/18 [==============================] - 0s 2ms/step - loss: 56.5209 - accuracy: 0.3726
Epoch 8/100
18/18 [==============================] - 0s 2ms/step - loss: 42.2173 - accuracy: 0.3726
Epoch 9/100
18/18 [==============================] - 0s 2ms/step - loss: 27.7430 - accuracy: 0.3726
Epoch 10/100
18/18 [==============================] - 0s 2ms/step - loss: 13.5202 - accuracy: 0.3

In [26]:
model.predict(x)[:15].reshape(-1)

array([0.0000000e+00, 1.9678982e-33, 3.8088676e-26, 2.2533536e-04,
       1.9171031e-09, 3.5802522e-10, 3.0648524e-29, 3.4542898e-14,
       1.9490719e-04, 1.0194182e-03, 1.6097358e-12, 2.6348626e-28,
       1.6283989e-04, 1.0000000e+00, 9.9999684e-01], dtype=float32)

In [27]:
y[:15]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])