# 1일차 Review : 같은 문제 다시 풀어보기

    학습은 10번으로!

In [1]:
from sklearn.datasets import load_iris

In [40]:
iris = load_iris()

In [41]:
x = iris.data
y = iris.target

In [42]:
x.shape, y.shape

((150, 4), (150,))

In [43]:
#####################
# 라이브러리 불러오기
#####################

import tensorflow as tf
from tensorflow import keras


In [44]:
#######################
# 어떤 전처리 작업 필요
# Hint : y.shape
#######################

# test 데이터는 미래의 데이터이기 때문에 split 후 전처리하는 것이 바람직 !

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2022)

import numpy as np
from tensorflow.keras.utils import to_categorical

class_n = len(np.unique(y_train))
y_train = to_categorical(y_train, class_n)
y_test = to_categorical(y_test, class_n)

In [45]:
x_train.shape, y_train.shape

((120, 4), (120, 3))

In [46]:
########
# 모델링
########

keras.backend.clear_session()

model = keras.models.Sequential()

model.add(keras.layers.Input(shape=(4, )))
model.add(keras.layers.Dense(3, activation='softmax'))

model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

In [47]:
###########
# 모델 학습
###########

model.fit(x_train, y_train, epochs=10, verbose=1)

Epoch 1/10
4/4 [==============================] - 0s 3ms/step - loss: 5.2461 - accuracy: 0.3083
Epoch 2/10
4/4 [==============================] - 0s 3ms/step - loss: 5.1743 - accuracy: 0.3083
Epoch 3/10
4/4 [==============================] - 0s 3ms/step - loss: 5.1011 - accuracy: 0.3083
Epoch 4/10
4/4 [==============================] - 0s 4ms/step - loss: 5.0299 - accuracy: 0.3083
Epoch 5/10
4/4 [==============================] - 0s 4ms/step - loss: 4.9575 - accuracy: 0.3083
Epoch 6/10
4/4 [==============================] - 0s 4ms/step - loss: 4.8825 - accuracy: 0.3083
Epoch 7/10
4/4 [==============================] - 0s 3ms/step - loss: 4.8131 - accuracy: 0.3083
Epoch 8/10
4/4 [==============================] - 0s 3ms/step - loss: 4.7406 - accuracy: 0.3083
Epoch 9/10
4/4 [==============================] - 0s 3ms/step - loss: 4.6706 - accuracy: 0.3083
Epoch 10/10
4/4 [==============================] - 0s 3ms/step - loss: 4.6003 - accuracy: 0.3083


In [48]:
###########
# 모델 예측
###########

y_pred = model.predict(x_test)

In [49]:
print(y_pred.argmax(axis=1))
print(y_test.argmax(axis=1))

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
[2 2 0 2 0 0 1 1 0 1 1 2 1 2 2 0 1 2 2 1 0 0 2 0 2 2 2 0 1 2]


# 히든 레이어 추가하여 모델링! (Functional API)

    히든 레이어 2개를 추가하여 다시 모델링!
    히든 레이어 노드 수 : 32
    히든 레이어 activation = 'relu'

In [65]:
########
# 모델링
########

# 1. 세션 클리어
keras.backend.clear_session()

# 2. 레이어 사슬처럼 엮기
il = keras.layers.Input(shape=(4,))
hl = keras.layers.Dense(32, activation='relu', name='hidden1')(il)
hl = keras.layers.Dense(32, activation='relu', name='hidden2')(hl)
ol = keras.layers.Dense(3, activation='softmax')(hl)
# 엮는 것만 잘 엮으면 변수명이 동일해도 상관이 없음

# 3. 모델의 시작과 끝 지정
model = keras.models.Model(il, ol)

# 4. 모델 컴파일
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

In [66]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 4)]               0         
                                                                 
 hidden1 (Dense)             (None, 32)                160       
                                                                 
 hidden2 (Dense)             (None, 32)                1056      
                                                                 
 dense (Dense)               (None, 3)                 99        
                                                                 
Total params: 1,315
Trainable params: 1,315
Non-trainable params: 0
_________________________________________________________________


In [70]:
###########
# 모델 학습
###########

model.fit(x_train, y_train, epochs=10, verbose=1)

Epoch 1/10
4/4 [==============================] - 0s 4ms/step - loss: 0.1250 - accuracy: 0.9833
Epoch 2/10
4/4 [==============================] - 0s 4ms/step - loss: 0.1231 - accuracy: 0.9833
Epoch 3/10
4/4 [==============================] - 0s 4ms/step - loss: 0.1213 - accuracy: 0.9917
Epoch 4/10
4/4 [==============================] - 0s 4ms/step - loss: 0.1174 - accuracy: 0.9833
Epoch 5/10
4/4 [==============================] - 0s 5ms/step - loss: 0.1163 - accuracy: 0.9833
Epoch 6/10
4/4 [==============================] - 0s 3ms/step - loss: 0.1153 - accuracy: 0.9833
Epoch 7/10
4/4 [==============================] - 0s 4ms/step - loss: 0.1116 - accuracy: 0.9833
Epoch 8/10
4/4 [==============================] - 0s 4ms/step - loss: 0.1106 - accuracy: 0.9833
Epoch 9/10
4/4 [==============================] - 0s 4ms/step - loss: 0.1078 - accuracy: 0.9833
Epoch 10/10
4/4 [==============================] - 0s 4ms/step - loss: 0.1070 - accuracy: 0.9917


In [71]:
###########
# 모델 예측
###########

y_pred = model.predict(x_test)

In [72]:
print(y_pred.argmax(axis=1))
print(y_test.argmax(axis=1))

[2 2 0 2 0 0 1 1 0 1 1 1 1 2 2 0 1 1 2 1 0 0 2 0 2 1 2 0 2 2]
[2 2 0 2 0 0 1 1 0 1 1 2 1 2 2 0 1 2 2 1 0 0 2 0 2 2 2 0 1 2]
