# 1일차 Review : 같은 문제 다시 풀어보기

    학습은 10번으로!

In [10]:
from sklearn.datasets import load_breast_cancer

In [2]:
cancer = load_breast_cancer()

In [3]:
x = cancer.data
y = cancer.target

In [4]:
x.shape, y.shape

((569, 30), (569,))

In [7]:
y[:5]

array([0, 0, 0, 0, 0])

In [11]:
from sklearn.model_selection import train_test_split

In [26]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2022)

In [27]:
#####################
# 라이브러리 불러오기
#####################

import tensorflow as tf
from tensorflow import keras


In [35]:
########
# 모델링
########

keras.backend.clear_session()

il = keras.layers.Input(shape=(30,), name='inputLayer')
ol = keras.layers.Dense(1, activation='sigmoid', name='outputLayer')(il)

model = keras.models.Model(il, ol)

model.compile(loss='binary_crossentropy', metrics=['accuracy'], optimizer='adam')

In [36]:
model.summary()
# functional은 input 레이어가 표현 됨
# sequancial은 다음 레이어에 포함되어 표현
# param = 30+1

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 inputLayer (InputLayer)     [(None, 30)]              0         
                                                                 
 outputLayer (Dense)         (None, 1)                 31        
                                                                 
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [ ]:
###########
# 모델 학습
###########

model.fit(x_train, y_train, epochs=100, verbose=1)


In [33]:
###########
# 모델 예측
###########

y_pred = model.predict(x_test)

print(y_pred[:15])
print(y_test[:15])

[[9.9984539e-01]
 [1.0000000e+00]
 [9.9999654e-01]
 [1.0000000e+00]
 [1.0000000e+00]
 [1.0000000e+00]
 [1.0870099e-03]
 [7.4397818e-34]
 [4.5860023e-05]
 [0.0000000e+00]
 [0.0000000e+00]
 [1.0211173e-14]
 [1.2857452e-16]
 [8.3133305e-27]
 [3.4738630e-02]]
[1 1 0 1 1 1 1 0 0 0 0 0 0 0 1]


# 히든 레이어 추가하여 모델링!

    히든 레이어 2개를 추가하여 다시 모델링!
    히든 레이어 노드 수 : 32
    히든 레이어 activation = 'relu'

In [41]:
########
# 모델링
########

keras.backend.clear_session()

il = keras.layers.Input(shape=(30,), name='inputLayer')
hl1 = keras.layers.Dense(32, activation='relu')(il)
hl2 = keras.layers.Dense(32, activation='relu')(hl1)
ol = keras.layers.Dense(1, activation='sigmoid', name='outputLayer')(hl2)

model = keras.models.Model(il, ol)

model.compile(loss='binary_crossentropy', metrics=['accuracy'], optimizer='adam')

In [42]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 inputLayer (InputLayer)     [(None, 30)]              0         
                                                                 
 dense (Dense)               (None, 32)                992       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 outputLayer (Dense)         (None, 1)                 33        
                                                                 
Total params: 2,081
Trainable params: 2,081
Non-trainable params: 0
_________________________________________________________________


In [43]:
###########
# 모델 학습
###########

model.fit(x_train, y_train, epochs=100, verbose=1)

Epoch 1/100
15/15 [==============================] - 1s 2ms/step - loss: 20.9066 - accuracy: 0.4220
Epoch 2/100
15/15 [==============================] - 0s 2ms/step - loss: 3.1606 - accuracy: 0.6615
Epoch 3/100
15/15 [==============================] - 0s 2ms/step - loss: 1.2106 - accuracy: 0.7429
Epoch 4/100
15/15 [==============================] - 0s 2ms/step - loss: 0.8939 - accuracy: 0.7824
Epoch 5/100
15/15 [==============================] - 0s 3ms/step - loss: 0.7025 - accuracy: 0.8374
Epoch 6/100
15/15 [==============================] - 0s 3ms/step - loss: 0.5899 - accuracy: 0.8264
Epoch 7/100
15/15 [==============================] - 0s 6ms/step - loss: 0.4523 - accuracy: 0.8703
Epoch 8/100
15/15 [==============================] - 0s 6ms/step - loss: 0.3315 - accuracy: 0.8857
Epoch 9/100
15/15 [==============================] - 0s 3ms/step - loss: 0.3861 - accuracy: 0.8659
Epoch 10/100
15/15 [==============================] - 0s 4ms/step - loss: 0.4570 - accuracy: 0.8747
Epoch 11

In [56]:
###########
# 모델 예측
###########

import numpy as np

y_pred = model.predict(x_test)
y_pred = np.where(y_pred >= 0.5, 1, 0)

print(y_pred.reshape(-1))
print(y_test)


[1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 0 1 1 1 1 0 0 1 1 1 0 1 1 1 0 0 1 0 0
 1 0 1 1 0 0 1 0 1 0 1 0 0 1 0 0 1 0 0 1 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1
 0 1 0 1 0 1 1 1 0 1 1 0 0 0 1 0 1 0 1 1 0 1 1 1 1 1 0 1 0 0 0 1 1 0 0 1 1
 1 0 1]
[1 1 0 1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 0 0
 1 0 1 1 0 0 1 0 1 0 1 0 0 1 0 0 1 0 0 1 1 1 1 0 1 1 0 0 1 1 1 0 1 1 0 1 1
 0 1 0 0 0 1 1 1 0 1 1 0 0 0 1 0 1 0 1 1 0 1 1 1 1 1 0 1 0 0 1 1 1 0 0 1 1
 1 0 1]
